services:
  # React Client
  vending-client:
    build:
      context: ./vending-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - vending-services
    networks:
      - app-network

  # NestJS Service
  vending-services:
    build:
      context: ./vending-services
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # NestJS default port
    environment:
      - PORT=4000
      - DATABASE_ENDPOINT=vending-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=vending-db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=adm1nP@ssw0rd
      - DB_LOG=false
      - INIT_MOCK_DATA=true
    depends_on:
      - vending-db
    networks:
      - app-network

  # PostgreSQL Database
  vending-db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm1nP@ssw0rd
      POSTGRES_DB: vending-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

# Network definition
networks:
  app-network:

# Volumes for persistent storage
volumes:
  postgres-data:
